# Generated by Django 5.1.3 on 2024-12-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_name', models.CharField(max_length=255, null=True)),
                ('os_name', models.CharField(max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(null=True, unpack_ipv4=True)),
                ('capture_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
