# Generated by Django 5.1.3 on 2024-12-01 12:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='ip_address',
            field=models.GenericIPAddressField(default=uuid.uuid1, null=True, unique=True, unpack_ipv4=True),
        ),
    ]
