# Generated by Django 5.1.3 on 2024-12-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveur', '0004_clientinfo_nom_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
